### ISSUE TITLE
Replace rayon with a fast async library

### ISSUE THREAD

**Issue by bijancn** [bijancn/gitlabctl#1]
crayon was tested for adding parallelism but it's not really helping for this case.

The desired result would be to speed up a typical call like this
```
target/debug/gitlabctl get environments -n server
Retrieved 20 projects          [2.88s]
Retrieved 49 environments      [2.29s]
Retrieved environments details [6.64s]
PROJECT                     ENVIRONMENT  DEPLOYMENT           COMMIT    UPDATED
...
```

**Comment by Baev1** [comment]
Hi! do you have any particular library in mind?

**Comment by bijancn** [comment]
Hi @Baev1 ! @ChetanBhasin is adding https://tokio.rs as far as I know. But if you want to contribute, you can have a look at https://github.com/bijancn/gitlabctl/issues/2 , https://github.com/bijancn/gitlabctl/issues/3 or https://github.com/bijancn/gitlabctl/issues/4

**Comment by bijancn** [comment]
Closed by https://github.com/bijancn/gitlabctl/pull/8
